/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import stock.Tools;
import datta.Detaille;
import datta.Produit;
import static forms.Home.setconnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Alilo
 */
public class Commande extends javax.swing.JFrame {
      private static String url;
    private static Connection con;
    private static Statement stmt;
    private static ResultSet rs;
    static String numclient,nomclient,total_som;
    
    int count_produit,reference;
      String values[];
      String designation_produit;
      double somme=0;
     void handle()
    {
        list_produit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                designation_produit=list_produit.getSelectedItem().toString();
               // Tools.msgBox(designation_produit);
                getreference();
             
                   
                
          //  Tools.msgBox(list_fournisseur.getSelectedItem().toString()+"  "+String.valueOf(id_four));
            }
        });
    }
    
    public static void seturl()
    {
        url="jdbc:sqlite:stock.db";
       // url="jdbc:mysql://localhost/"+dbname+"?user=root&password=mypass";
    }
    ArrayList<String> list_f=new ArrayList<>();
    public static void setconnection()
    {
        try
        {
           con=null;
         
            seturl();
            con=DriverManager.getConnection(url);
           System.out.println("Opened database successfully");
            
        }
        catch(SQLException ex)
        {
           
        }
    }

    /**
     * Creates new form Commande
     */
    public Commande() {
        initComponents();
    }
    void count_produit() throws SQLException
    {
       try{
           
            setconnection();
            String select ="select count(*) from produit ";
            stmt=con.createStatement();
	     rs=stmt.executeQuery(select);
             while(rs.next()){
                count_produit= Integer.parseInt(rs.getString(1));
             }
            
        }catch(Exception e){
            e.printStackTrace();
        }finally{
           
            con.close();
            stmt.close();
            rs.close();
        }
    }
     void info_first_produit() throws SQLException
    {
       try{
           
            setconnection();
            String select ="SELECT * from produit LIMIT 1;";
            stmt=con.createStatement();
	     rs=stmt.executeQuery(select);
             while(rs.next()){
               reference=Integer.parseInt(rs.getString(1));
             //  Tools.msgBox(String.valueOf(reference));
               reststock.setText(rs.getString(7));
               prixunitaire.setText(rs.getString(6));
             }
            
        }catch(Exception e){
            e.printStackTrace();
        }finally{
           
            con.close();
            stmt.close();
            rs.close();
        }
    }
     void list_produit() throws SQLException
    {
        try{
            count_produit();
            values=new String[count_produit];
            int i=0;
            setconnection();
            String select ="select designation from produit ";
            stmt=con.createStatement();
	     rs=stmt.executeQuery(select);
             while(rs.next()){
                 values[i]=rs.getString(1);
                 i++;
             }
            
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            con.close();
            stmt.close();
            rs.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        list_produit = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txtqte = new javax.swing.JTextField();
        reststock = new javax.swing.JTextField();
        prixunitaire = new javax.swing.JTextField();
        txtmontant = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        detail_commande = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtsomme = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtnumclient = new javax.swing.JTextField();
        txtnomclient = new javax.swing.JTextField();
        txtnumcommande = new javax.swing.JTextField();
        txtprenomclient = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 3));

        list_produit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        list_produit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));

        jLabel21.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel21.setText("Selectionner un Produit");

        jLabel22.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel22.setText("Quantité");

        jLabel23.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel23.setText("Reste dans Stock");

        jLabel24.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel24.setText("Prix Unitaire");

        jLabel25.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel25.setText("Montant ");

        jButton6.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jButton6.setText("Ajouter");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtqte.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        txtqte.setForeground(new java.awt.Color(255, 51, 51));
        txtqte.setText("1");
        txtqte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        txtqte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqteActionPerformed(evt);
            }
        });
        txtqte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtqteKeyPressed(evt);
            }
        });

        reststock.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        reststock.setForeground(new java.awt.Color(255, 51, 51));
        reststock.setText("0");
        reststock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        reststock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reststockActionPerformed(evt);
            }
        });

        prixunitaire.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        prixunitaire.setForeground(new java.awt.Color(255, 51, 51));
        prixunitaire.setText("0.0");
        prixunitaire.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        prixunitaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixunitaireActionPerformed(evt);
            }
        });

        txtmontant.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        txtmontant.setForeground(new java.awt.Color(255, 51, 51));
        txtmontant.setText("0.0");
        txtmontant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        txtmontant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmontantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(list_produit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(txtqte, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reststock, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(prixunitaire, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(prixunitaire, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmontant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reststock, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtqte, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(list_produit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        detail_commande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reference", "designation", "Quantité", "Prix", "Montant"
            }
        ));
        jScrollPane4.setViewportView(detail_commande);

        jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 204), 2, true));

        jLabel26.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel26.setText("Somme :");

        txtsomme.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        txtsomme.setForeground(new java.awt.Color(255, 51, 51));
        txtsomme.setText("0.0");
        txtsomme.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        txtsomme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsommeActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel27.setText("DA");

        jButton7.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jButton7.setText("Caissé");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 4, true));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsomme, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsomme, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/if_Print_56266.png"))); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 2), "Information Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 18), new java.awt.Color(51, 0, 51))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel28.setText("N° de Client :");

        jLabel29.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel29.setText("Nom Client");

        jLabel30.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel30.setText("Prenom Client");

        txtnumclient.setEditable(false);
        txtnumclient.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        txtnumclient.setForeground(new java.awt.Color(255, 51, 51));
        txtnumclient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        txtnumclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumclientActionPerformed(evt);
            }
        });

        txtnomclient.setEditable(false);
        txtnomclient.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtnomclient.setForeground(new java.awt.Color(255, 51, 51));
        txtnomclient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        txtnomclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomclientActionPerformed(evt);
            }
        });

        txtnumcommande.setEditable(false);
        txtnumcommande.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtnumcommande.setForeground(new java.awt.Color(255, 51, 51));
        txtnumcommande.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        txtnumcommande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumcommandeActionPerformed(evt);
            }
        });

        txtprenomclient.setEditable(false);
        txtprenomclient.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txtprenomclient.setForeground(new java.awt.Color(255, 51, 51));
        txtprenomclient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 2, true));
        txtprenomclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomclientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumclient, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txtnomclient, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 612, Short.MAX_VALUE)
                        .addComponent(txtnumcommande, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(txtprenomclient, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnumcommande, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnumclient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnomclient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtprenomclient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1517, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtqteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqteActionPerformed

    private void reststockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reststockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reststockActionPerformed

    private void prixunitaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixunitaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixunitaireActionPerformed

    private void txtmontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmontantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontantActionPerformed

    private void txtsommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsommeActionPerformed

    private void txtnumclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumclientActionPerformed

    private void txtnomclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomclientActionPerformed

    private void txtnumcommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumcommandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumcommandeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            list_produit();
            info_first_produit();
             double rest=Double.parseDouble(reststock.getText());
            double qte=Double.parseDouble(txtqte.getText());
            double prix=Double.parseDouble(prixunitaire.getText());
            if(rest>=qte){
                 double montant =qte*prix;
             txtmontant.setText(String.valueOf(montant));}
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        list_produit.setModel(new DefaultComboBoxModel(values));
        txtnumclient.setText(Home.nclient);
        txtnomclient.setText(Home.nomclient);
        txtprenomclient.setText(Home.prenomclient);
        txtnumcommande.setText(dbase.Go.GetAutoNumber("commande", "id_commande"));
        handle();
          datta.Commande c=new datta.Commande();
       c.setId_commande(Integer.parseInt(txtnumcommande.getText()));
       c.setClient(Integer.parseInt(txtnumclient.getText()));
       c.add();
          
      
            
        
    }//GEN-LAST:event_formWindowOpened
   
    void getreference()
    {
        try {
            setconnection();
            String select ="select reference,quantite_reste,prix_vente from produit where designation='"+designation_produit+"'";
            stmt=con.createStatement();
            rs=stmt.executeQuery(select);
           while(rs.next()){
                reference= Integer.parseInt(rs.getString(1));
                reststock.setText(rs.getString(2));
                prixunitaire.setText(rs.getString(3));
            }
        } catch (Exception e) {
        }finally{
            try {
                con.close();
                stmt.close();
                rs.close();
            } catch (Exception e) {
            }
        }
        
    }
     
    private void txtprenomclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomclientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomclientActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        datta.Detaille dc=new Detaille();
        dc.setCommande(Integer.parseInt(txtnumcommande.getText()));
        dc.setReference(reference);
        dc.setQte(Double.parseDouble(txtqte.getText()));
        dc.add();
        somme=somme+Double.parseDouble(txtmontant.getText());
        txtsomme.setText(String.valueOf(somme));
        double rest=Double.parseDouble(reststock.getText());
         double qte=Double.parseDouble(txtqte.getText());
         double nqte=rest-qte;
         Produit p=new Produit();
         p.setId(reference);
         p.setQtereste(nqte);
         p.update_qterest();
        getreference();
        dbase.Go.fillToJtable("select reference,designation,quantite,prix_vente,quantite*prix_vente from commande_data where commande="+Integer.parseInt(txtnumcommande.getText()), detail_commande);
        reststock.setText(String.valueOf(nqte));
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtqteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double rest=Double.parseDouble(reststock.getText());
            double qte=Double.parseDouble(txtqte.getText());
            double prix=Double.parseDouble(prixunitaire.getText());
            if(rest>=qte){
                 double montant =qte*prix;
             txtmontant.setText(String.valueOf(montant));
            }else
            {
                Tools.msgBox("Quantité n'est pas valide !!");
                txtqte.setText(String.valueOf(rest));
            }
           
        }
    }//GEN-LAST:event_txtqteKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       numclient=txtnumclient.getText();
       nomclient=txtnomclient.getText()+" "+txtprenomclient.getText();
       total_som=txtsomme.getText();
       Tools.openForm(new Versement());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tools.printreport(detail_commande, txtnomclient.getText()+" "+txtprenomclient.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Commande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detail_commande;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> list_produit;
    private javax.swing.JTextField prixunitaire;
    private javax.swing.JTextField reststock;
    private javax.swing.JTextField txtmontant;
    private javax.swing.JTextField txtnomclient;
    private javax.swing.JTextField txtnumclient;
    private javax.swing.JTextField txtnumcommande;
    private javax.swing.JTextField txtprenomclient;
    private javax.swing.JTextField txtqte;
    private javax.swing.JTextField txtsomme;
    // End of variables declaration//GEN-END:variables
}
